### ISSUE TITLE
 il faut pas justement mettre les vraies coordonnées sinon on peut pas changer la taille des cubes

### ISSUE THREAD

**Issue by micktaiwan** [micktaiwan/voxelgame#4]

**Comment by ddaydd** [comment]
Tu peux mettre les coordonnées et le type de cube, modele non?

**Comment by micktaiwan** [comment]
mettre le type c'est déjà le cas
mais il ne faut pas mettre les vrais pixels, mais les coordonnées logiques, sinon si un jour tu veux diminuer lataille d'un cube, les cubes seront espacés
